events {
    worker_connections 64;
}

http {
    server {
        listen 80;

        location /g1/ {
            proxy_pass http://g1:8000/;
        }
        location /g2/ {
            proxy_pass http://g2:8000/;
        }
        location /g3/ {
            proxy_pass http://g3:8000/;
        }
        location /g4/ {
            proxy_pass http://g4:8000/;
        }
        location /g5/ {
            proxy_pass http://g5:8000/;
        }
        location /g6/ {
            proxy_pass http://g6:8000/;
        }

        location = / {
            return 302 /g1/;
        }
    }
}
