apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lcls-surrogate-lab
resources:
  - namespace.yaml
  - configmap.yaml
  - statefulset.yaml
  - services.yaml
  - ingress.yaml

images:
  - name: ghcr.io/slaclab/lcls-surrogate-lab
    newTag: latest
